### ISSUE TITLE
Server Build Linux amd64 Error !

### ISSUE THREAD

**Issue by badboycxcc** [Enelg52/KittyStager#11]
MacBook-Pro :: C2/KittyStager/server ‹main*› » go env -w GOOS=windows GOARCH=amd64
MacBook-Pro :: C2/KittyStager/server ‹main*› » go build                           
MacBook-Pro :: C2/KittyStager/server ‹main*› » ls                                 
api        server.exe server.go
MacBook-Pro :: C2/KittyStager/server ‹main*› » go env -w GOOS=linux GOARCH=amd64  
MacBook-Pro :: C2/KittyStager/server ‹main*› » go build                         
package KittyStager/server
	imports KittyStager/kitten/malware
	imports golang.org/x/sys/windows: build constraints exclude all Go files in /Users/xxxxxx/go/pkg/mod/golang.org/x/sys@v0.6.0/windows
MacBook-Pro :: C2/KittyStager/server ‹main*› »

**Comment by Enelg52** [comment]
Hi ! Should be fixed now !

**Comment by Enelg52** [comment]
I just added GitHub workflow, this should not append again

**Comment by badboycxcc** [comment]
Yes, it works well now. It's cool.
<img width="468" alt="截屏2023-03-17 下午8 37 16" src="https://user-images.githubusercontent.com/72059221/225906759-c86d8168-5879-47b6-96aa-8f4a974fbcd1.png">
